@php($editing = isset($task))
<form method="POST" action="{{ $editing ? route('internal.tasks.update', $task) : route('internal.tasks.store', $project) }}" enctype="multipart/form-data" class="space-y-5">
    @csrf
    @if ($editing) @method('PATCH') <input type="hidden" name="version" value="{{ $task->version }}"> @endif
    <div><x-label for="{{ $formPrefix }}-title">Task name</x-label><x-input id="{{ $formPrefix }}-title" name="title" value="{{ old('title', $task->title ?? '') }}" required /><x-field-error name="title" /></div>
    <div><x-label for="{{ $formPrefix }}-description">Description</x-label><x-textarea id="{{ $formPrefix }}-description" name="description" rows="4">{{ old('description', $task->description ?? '') }}</x-textarea><x-field-error name="description" /></div>
    <div class="grid gap-4 sm:grid-cols-2">
        <div><x-label for="{{ $formPrefix }}-status">Status</x-label><x-select id="{{ $formPrefix }}-status" name="status_public_id" required>@foreach ($statuses as $status)<option value="{{ $status->public_id }}" @selected(old('status_public_id', $task->status->public_id ?? $defaultStatus?->public_id) === $status->public_id)>{{ $status->name }}</option>@endforeach</x-select></div>
        <div><x-label for="{{ $formPrefix }}-priority">Priority</x-label><x-select id="{{ $formPrefix }}-priority" name="priority" required>@foreach ($priorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority', $task->priority->value ?? 'medium') === $priority->value)>{{ $priority->label() }}</option>@endforeach</x-select></div>
        <div><x-label for="{{ $formPrefix }}-category">Category</x-label><x-select id="{{ $formPrefix }}-category" name="category_public_id"><option value="">No category</option>@foreach ($categories as $category)<option value="{{ $category->public_id }}" @selected(old('category_public_id', $task->category?->public_id ?? '') === $category->public_id)>{{ $category->name }}</option>@endforeach</x-select></div>
        <div><x-label for="{{ $formPrefix }}-milestone">Milestone</x-label><x-select id="{{ $formPrefix }}-milestone" name="milestone_public_id"><option value="">No milestone</option>@foreach ($milestones as $milestone)<option value="{{ $milestone->public_id }}" @selected(old('milestone_public_id', $task->milestone?->public_id ?? '') === $milestone->public_id)>{{ $milestone->name }} · {{ $milestone->target_date->format('M j') }}</option>@endforeach</x-select><x-field-error name="milestone_public_id" /></div>
        <div><x-label for="{{ $formPrefix }}-estimate">Estimate (minutes)</x-label><x-input id="{{ $formPrefix }}-estimate" type="number" min="1" name="estimate_minutes" value="{{ old('estimate_minutes', $task->estimate_minutes ?? '') }}" /></div>
        <div><x-label for="{{ $formPrefix }}-start">Start</x-label><x-input id="{{ $formPrefix }}-start" type="datetime-local" name="start_at" value="{{ old('start_at', isset($task) ? $task->start_at?->format('Y-m-d\TH:i') : '') }}" /></div>
        <div><x-label for="{{ $formPrefix }}-due">Due</x-label><x-input id="{{ $formPrefix }}-due" type="datetime-local" name="due_at" value="{{ old('due_at', isset($task) ? $task->due_at?->format('Y-m-d\TH:i') : '') }}" /><x-field-error name="due_at" /></div>
    </div>
    <fieldset><legend class="text-sm font-semibold text-slate-700 dark:text-slate-200">Assignees</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach ($projectMembers as $membership)<label class="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700"><input type="checkbox" name="assignee_public_ids[]" value="{{ $membership->user->public_id }}" class="rounded border-slate-300 text-orbit-600 focus:ring-orbit-500" @checked(in_array($membership->user->public_id, old('assignee_public_ids', isset($task) ? $task->assignees->pluck('public_id')->all() : [])))><span>{{ $membership->user->name }}</span></label>@endforeach</div><x-field-error name="assignee_public_ids" /></fieldset>
    <div><x-label for="{{ $formPrefix }}-attachments">{{ $editing ? 'Add attachments' : 'Attachments' }}</x-label><input id="{{ $formPrefix }}-attachments" type="file" name="attachments[]" multiple class="block w-full rounded-xl border border-slate-200 bg-white p-2.5 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-orbit-50 file:px-3 file:py-2 file:font-semibold file:text-orbit-700 dark:border-slate-700 dark:bg-slate-900"><p class="mt-1 text-xs text-slate-500">Up to {{ number_format(config('orbitra.max_file_upload_kb') / 1024) }} MB each. Images, PDF, Office, text, or ZIP.</p><x-field-error name="attachments.0" /></div>
    <div class="flex justify-end gap-3">{{ $cancel ?? '' }}<x-button>{{ $editing ? 'Save task' : 'Create task' }}</x-button></div>
</form>
