@extends('layouts.app')

@section('title', $project->name.' Board')
@section('page-title', $project->name)

@section('content')
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm text-slate-500">Projects / {{ $project->name }}</p><h2 class="mt-1 text-2xl font-bold tracking-tight">Kanban board</h2></div><div class="flex gap-2">@can('manageWorkflow', [App\Models\Task::class, $project])<details class="relative"><summary class="flex min-h-11 cursor-pointer list-none items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold">Manage status</summary><div class="absolute right-0 z-20 mt-2 w-72 rounded-2xl border border-slate-200 bg-white p-4 shadow-xl"><form method="POST" action="{{ route('internal.task-statuses.store', $project) }}" class="space-y-3">@csrf<x-input name="name" placeholder="Status name" required/><div class="grid grid-cols-2 gap-2"><x-input type="color" name="color" value="#6366f1"/><x-select name="category">@foreach(App\Enums\TaskStatusCategory::cases() as $category)<option value="{{ $category->value }}">{{ $category->label() }}</option>@endforeach</x-select></div><x-button class="w-full">Add status</x-button></form></div></details>@endcan @can('create', [App\Models\Task::class, $project])<x-button type="button" onclick="document.getElementById('new-task-dialog').showModal()"><x-icon name="plus"/>Add task</x-button>@endcan</div></div>
    @include('app.projects._tabs', ['project' => $project])
    <div class="mt-5 flex gap-4 overflow-x-auto pb-5" data-kanban>
        @foreach($statuses as $status)
            <section class="w-[310px] shrink-0 rounded-2xl bg-slate-100/80 p-3 dark:bg-slate-900" data-status-column data-status-id="{{ $status->public_id }}" data-status-category="{{ $status->category->value }}">
                <header class="mb-3 flex items-center justify-between"><div class="flex items-center gap-2"><span class="size-2.5 rounded-full" style="background:{{ $status->color }}"></span><h3 class="font-bold">{{ $status->name }}</h3><span data-task-count class="rounded-full bg-white px-2 py-0.5 text-xs text-slate-500 shadow-sm dark:bg-slate-800">{{ $status->tasks->count() }}</span></div>@can('update', $status)<details class="relative"><summary class="grid size-8 cursor-pointer list-none place-items-center rounded-lg text-slate-500 hover:bg-white">•••</summary><div class="absolute right-0 z-20 mt-1 w-64 rounded-2xl border border-slate-200 bg-white p-3 shadow-xl"><div class="mb-3 grid grid-cols-2 gap-2">@php($statusIds = $statuses->pluck('public_id')->all()) @if(!$loop->first)<form method="POST" action="{{ route('internal.task-statuses.reorder', $project) }}">@csrf @foreach(array_values(array_merge(array_slice($statusIds, 0, $loop->index - 1), [$status->public_id, $statusIds[$loop->index - 1]], array_slice($statusIds, $loop->index + 1))) as $statusId)<input type="hidden" name="status_public_ids[]" value="{{ $statusId }}">@endforeach<x-button variant="secondary" class="w-full" aria-label="Move {{ $status->name }} left">← Left</x-button></form>@else<span></span>@endif @if(!$loop->last)<form method="POST" action="{{ route('internal.task-statuses.reorder', $project) }}">@csrf @foreach(array_values(array_merge(array_slice($statusIds, 0, $loop->index), [$statusIds[$loop->index + 1], $status->public_id], array_slice($statusIds, $loop->index + 2))) as $statusId)<input type="hidden" name="status_public_ids[]" value="{{ $statusId }}">@endforeach<x-button variant="secondary" class="w-full" aria-label="Move {{ $status->name }} right">Right →</x-button></form>@endif</div><form method="POST" action="{{ route('internal.task-statuses.update', $status) }}" class="space-y-2">@csrf @method('PATCH')<x-input name="name" value="{{ $status->name }}" required/><div class="grid grid-cols-2 gap-2"><x-input type="color" name="color" value="{{ $status->color }}"/><x-select name="category">@foreach(App\Enums\TaskStatusCategory::cases() as $category)<option value="{{ $category->value }}" @selected($status->category === $category)>{{ $category->label() }}</option>@endforeach</x-select></div><x-button variant="secondary" class="w-full">Save</x-button></form>@if(!$status->is_system)<form method="POST" action="{{ route('internal.task-statuses.destroy', $status) }}" class="mt-3 space-y-2 border-t border-slate-100 pt-3" onsubmit="return confirm('Archive this status and move its tasks?')">@csrf @method('DELETE')<x-select name="replacement_status_public_id" required><option value="">Move tasks to…</option>@foreach($statuses->where('id','!=',$status->id) as $replacement)<option value="{{ $replacement->public_id }}">{{ $replacement->name }}</option>@endforeach</x-select><x-button variant="danger" class="w-full">Archive status</x-button></form>@endif</div></details>@endcan</header>
                <div class="min-h-24 space-y-3" data-task-list>
                    @foreach($status->tasks as $task)
                        <article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition dark:border-slate-800 dark:bg-slate-950" data-task-card data-task-id="{{ $task->public_id }}" data-version="{{ $task->version }}" data-move-url="{{ route('internal.tasks.move', $task) }}" data-blocked="{{ $task->isBlocked() ? 'true' : 'false' }}" @can('update',$task) draggable="true" @endcan>
                            <div class="flex items-start justify-between gap-3"><div class="flex flex-wrap gap-1">@if($task->category)<span class="rounded-full px-2 py-1 text-[11px] font-bold" style="color:{{ $task->category->color }};background:color-mix(in srgb, {{ $task->category->color }} 12%, transparent)">{{ $task->category->name }}</span>@endif @if($task->isBlocked())<span class="rounded-full bg-rose-100 px-2 py-1 text-[11px] font-bold text-rose-700 dark:bg-rose-950 dark:text-rose-200">Blocked</span>@endif</div><span class="text-xs font-semibold text-slate-400">{{ $task->priority->label() }}</span></div>
                            <h4 class="mt-3 font-bold leading-5"><a href="{{ route('app.tasks.show', $task) }}" class="hover:text-orbit-700">{{ $task->title }}</a></h4><p class="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{{ $task->description }}</p>
                            <div class="mt-4 flex items-center justify-between text-xs text-slate-500"><span class="{{ $task->due_at && !$task->completed_at && $task->due_at->isPast() ? 'font-semibold text-rose-600' : '' }}">{{ $task->due_at?->format('M j') ?? 'No due date' }}</span><span>{{ $task->checklistItems->where('is_completed', true)->count() }}/{{ $task->checklistItems->count() }} ✓</span></div>
                            <div class="mt-3 flex -space-x-1">@foreach($task->assignees->take(3) as $assignee)<x-avatar :src="filled($assignee->avatar_path) ? route('internal.users.avatar', $assignee) : null" :name="$assignee->name" size="size-7" class="border-2 border-white dark:border-slate-950" />@endforeach</div>
                        </article>
                    @endforeach
                </div>
                @can('create', [App\Models\Task::class, $project])<button type="button" class="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-slate-300 text-sm font-semibold text-slate-500 hover:border-orbit-400 hover:text-orbit-700" onclick="document.getElementById('new-task-status').value='{{ $status->public_id }}';document.getElementById('new-task-dialog').showModal()"><x-icon name="plus"/>Add task</button>@endcan
            </section>
        @endforeach
    </div>
    @can('create', [App\Models\Task::class, $project]) @include('app.tasks._create-dialog', ['defaultStatus' => $statuses->first()]) @endcan
@endsection
