@extends('layouts.app')

@section('title', $project->name.' Tasks')
@section('page-title', $project->name)

@section('content')
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm text-slate-500">Projects / {{ $project->name }}</p><h2 class="mt-1 text-2xl font-bold tracking-tight">Project tasks</h2></div>@can('create', [App\Models\Task::class, $project])<x-button type="button" onclick="document.getElementById('new-task-dialog').showModal()"><x-icon name="plus"/>Add task</x-button>@endcan</div>
    @include('app.projects._tabs', ['project' => $project])
    <form method="GET" class="mt-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><div class="relative min-w-64 flex-1"><x-icon name="search" class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><x-input name="search" value="{{ request('search') }}" placeholder="Search task" class="pl-9" /></div><x-select name="priority" class="sm:max-w-44"><option value="">All priorities</option>@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(request('priority') === $priority->value)>{{ $priority->label() }}</option>@endforeach</x-select><x-select name="blocked" class="sm:max-w-44"><option value="">All readiness</option><option value="1" @selected(request()->boolean('blocked'))>Blocked only</option></x-select><x-button variant="secondary">Filter</x-button></form>

    <form method="POST" action="{{ route('internal.tasks.bulk', $project) }}" x-data="{ action: 'status' }" class="mt-5">
        @csrf
        @can('create', [App\Models\Task::class, $project])
            <div class="mb-3 flex flex-wrap items-center gap-2 rounded-xl bg-slate-100 p-2 dark:bg-slate-800"><span class="px-2 text-xs font-bold uppercase tracking-wide text-slate-500">Bulk action</span><x-select name="action" x-model="action" class="sm:max-w-40"><option value="status">Change status</option><option value="priority">Change priority</option><option value="assignee">Set assignee</option><option value="archive">Archive</option></x-select><x-select name="status_public_id" x-show="action === 'status'" class="sm:max-w-44">@foreach($statuses as $status)<option value="{{ $status->public_id }}">{{ $status->name }}</option>@endforeach</x-select><x-select name="priority" x-show="action === 'priority'" class="sm:max-w-40">@foreach($priorities as $priority)<option value="{{ $priority->value }}">{{ $priority->label() }}</option>@endforeach</x-select><x-select name="assignee_public_id" x-show="action === 'assignee'" class="sm:max-w-48">@foreach($projectMembers as $membership)<option value="{{ $membership->user->public_id }}">{{ $membership->user->name }}</option>@endforeach</x-select><x-button variant="secondary">Apply to selected</x-button></div>
        @endcan
        <div class="space-y-4">
            @foreach($statuses as $status)
                @php($groupTasks = $tasksByStatus->get($status->id, collect()))
                <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900" x-data="{ open: true }">
                    <header class="flex items-center justify-between border-b border-slate-100 px-4 py-3 dark:border-slate-800"><button type="button" class="flex items-center gap-3 text-left" x-on:click="open = !open" :aria-expanded="open"><span class="size-2.5 rounded-full" style="background:{{ $status->color }}"></span><span class="font-bold">{{ $status->name }}</span><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-500 dark:bg-slate-800">{{ $groupTasks->count() }}</span><span class="text-slate-400" x-text="open ? '⌃' : '⌄'"></span></button>@can('create', [App\Models\Task::class, $project])<button type="button" class="inline-flex min-h-9 items-center gap-1 rounded-lg px-3 text-sm font-semibold text-orbit-700 hover:bg-orbit-50" onclick="document.getElementById('new-task-status').value='{{ $status->public_id }}';document.getElementById('new-task-dialog').showModal()"><x-icon name="plus"/>Add task</button>@endcan</header>
                    <div x-show="open" class="overflow-x-auto"><table class="min-w-[900px] w-full text-left text-sm"><thead class="bg-slate-50/80 text-xs uppercase tracking-wide text-slate-400 dark:bg-slate-900"><tr><th class="w-12 px-4 py-3"><span class="sr-only">Select</span></th><th class="px-3 py-3">Name</th><th class="px-3 py-3">Description</th><th class="px-3 py-3">Due date</th><th class="px-3 py-3">Assignee</th><th class="px-3 py-3">Priority</th><th class="px-3 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($groupTasks as $task)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td class="px-4 py-3"><input type="checkbox" name="task_public_ids[]" value="{{ $task->public_id }}" class="rounded border-slate-300 text-orbit-600 focus:ring-orbit-500" aria-label="Select {{ $task->title }}"></td><td class="px-3 py-3"><div class="flex items-center gap-2"><a href="{{ route('app.tasks.show', $task) }}" class="font-semibold hover:text-orbit-700">{{ $task->title }}</a>@if($task->isBlocked())<span class="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-bold text-rose-700 dark:bg-rose-950 dark:text-rose-200">Blocked</span>@endif</div>@if($task->milestone)<p class="mt-1 text-[10px] font-semibold text-violet-600">◆ {{ $task->milestone->name }}</p>@endif</td><td class="max-w-xs truncate px-3 py-3 text-slate-500">{{ $task->description ?: '—' }}</td><td class="px-3 py-3 {{ $task->due_at && !$task->completed_at && $task->due_at->isPast() ? 'font-semibold text-rose-600' : 'text-slate-500' }}">{{ $task->due_at?->format('M j, Y') ?? '—' }}</td><td class="px-3 py-3">{{ $task->assignees->pluck('first_name')->join(', ') ?: '—' }}</td><td class="px-3 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold dark:bg-slate-800">{{ $task->priority->label() }}</span></td><td class="px-3 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold" style="color:{{ $status->color }};background:color-mix(in srgb, {{ $status->color }} 12%, transparent)">{{ $status->name }}</span></td></tr>@empty<tr><td colspan="7" class="px-4 py-8 text-center text-sm text-slate-500">No tasks in this status.</td></tr>@endforelse</tbody></table></div>
                </section>
            @endforeach
        </div>
    </form>
    <div class="mt-5">{{ $tasks->links() }}</div>
    @if($archivedTasks->isNotEmpty())<details class="mt-8 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><summary class="cursor-pointer font-bold">Archived tasks ({{ $archivedTasks->count() }})</summary><div class="mt-4 space-y-2">@foreach($archivedTasks as $archivedTask)<div class="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><span class="text-sm font-semibold">{{ $archivedTask->title }}</span>@can('restore',$archivedTask)<form method="POST" action="{{ route('internal.tasks.restore',$archivedTask) }}">@csrf<x-button variant="secondary">Restore</x-button></form>@endcan</div>@endforeach</div></details>@endif
    @can('update',$workspace)<details class="mt-6 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><summary class="cursor-pointer text-sm font-bold">Task categories</summary><form method="POST" action="{{ route('internal.task-categories.store',$workspace) }}" class="mt-4 grid gap-3 sm:grid-cols-[1fr_100px_auto]">@csrf<x-input name="name" placeholder="Category name" required/><x-input type="color" name="color" value="#8b5cf6"/><x-button>Add category</x-button></form></details>@endcan
    @can('create', [App\Models\Task::class, $project]) @include('app.tasks._create-dialog', ['defaultStatus' => $statuses->first()]) @endcan
@endsection
