@extends('layouts.app')

@section('title', $task->title)
@section('page-title', 'Task detail')

@section('content')
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('app.projects.tasks', [$task->workspace, $task->project]) }}" class="text-sm font-semibold text-slate-500 hover:text-orbit-700">← {{ $task->project->name }}</a><div class="mt-3 flex flex-wrap items-center gap-3"><span class="size-2.5 rounded-full" style="background:{{ $task->status->color }}"></span><h2 class="text-2xl font-bold tracking-tight">{{ $task->title }}</h2><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{{ $task->priority->label() }}</span>@if($task->isBlocked())<span class="rounded-full bg-rose-100 px-2.5 py-1 text-xs font-bold text-rose-700 dark:bg-rose-950 dark:text-rose-200">Blocked</span>@endif</div></div><div class="flex gap-2">@can('update',$task)<form method="POST" action="{{ route('internal.tasks.duplicate',$task) }}">@csrf<x-button variant="secondary">Duplicate</x-button></form>@endcan @can('delete',$task)<form method="POST" action="{{ route('internal.tasks.destroy',$task) }}" onsubmit="return confirm('Archive this task?')">@csrf @method('DELETE')<x-button variant="danger">Archive</x-button></form>@endcan</div></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
        <div class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 dark:border-slate-800 dark:bg-slate-900">
                <div class="flex items-center justify-between"><h3 class="text-lg font-bold">Task details</h3><span class="text-xs text-slate-400">Version {{ $task->version }}</span></div>
                @can('update',$task)<div class="mt-6">@include('app.tasks._form', ['formPrefix' => 'edit-task', 'project' => $task->project, 'statuses' => $task->project->taskStatuses, 'defaultStatus' => $task->status])</div>@else<div class="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600">{{ $task->description ?: 'No description.' }}</div>@endcan
            </section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 dark:border-slate-800 dark:bg-slate-900" aria-labelledby="comments-title">
                <h3 id="comments-title" class="text-lg font-bold">Comments</h3>
                @can('update',$task)<form method="POST" action="{{ route('internal.task-comments.store',$task) }}" class="mt-4">@csrf<x-textarea name="body" rows="3" placeholder="Write a comment…" required></x-textarea><div class="mt-2 text-right"><x-button>Add comment</x-button></div></form>@endcan
                <div class="mt-6 space-y-4">@forelse($task->comments as $comment)<article class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold">{{ $comment->author->name }}</p><time class="text-xs text-slate-400">{{ $comment->created_at->diffForHumans() }} @if($comment->edited_at)· edited @endif</time></div>@can('delete',$comment)<form method="POST" action="{{ route('internal.task-comments.destroy',$comment) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Delete</button></form>@endcan</div><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $comment->body }}</p>@can('update',$comment)<details class="mt-3"><summary class="cursor-pointer text-xs font-semibold text-orbit-700">Edit</summary><form method="POST" action="{{ route('internal.task-comments.update',$comment) }}" class="mt-2">@csrf @method('PATCH')<x-textarea name="body" rows="2">{{ $comment->body }}</x-textarea><x-button class="mt-2" variant="secondary">Save comment</x-button></form></details>@endcan</article>@empty<p class="text-sm text-slate-500">No comments yet.</p>@endforelse</div>
            </section>
        </div>
        <aside class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" aria-labelledby="dependencies-title">
                <div class="flex items-center justify-between gap-3"><h3 id="dependencies-title" class="font-bold">Dependencies</h3><span class="rounded-full px-2.5 py-1 text-[11px] font-bold {{ $task->isBlocked() ? 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-200' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-200' }}">{{ $task->isBlocked() ? 'Blocked' : 'Ready' }}</span></div>
                <p class="mt-1 text-xs text-slate-500">FS/SS block starting; FF/SF constrain the schedule. Links may span projects in this workspace.</p>
                <div class="mt-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Waiting for</p><div class="mt-2 space-y-2">@forelse($task->dependencies as $dependency)<div class="flex items-center gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800/60"><span class="size-2 shrink-0 rounded-full {{ $dependency->completed_at ? 'bg-emerald-500' : 'bg-rose-500' }}"></span><div class="min-w-0 flex-1"><a href="{{ route('app.tasks.show', $dependency) }}" class="block truncate text-sm font-semibold hover:text-orbit-700">{{ $dependency->title }}</a><p class="truncate text-[10px] font-semibold uppercase tracking-wide text-slate-400">{{ strtoupper($dependency->pivot->type ?? 'fs') }}@if(($dependency->pivot->lag_minutes ?? 0) > 0) · +{{ $dependency->pivot->lag_minutes.'m' }}@endif @if($dependency->project_id !== $task->project_id)· {{ $dependency->project?->name }}@endif</p></div><span class="text-[10px] font-bold text-slate-400">{{ $dependency->completed_at ? 'Done' : 'Open' }}</span>@can('update',$task)<form method="POST" action="{{ route('internal.task-dependencies.destroy', [$task, $dependency]) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600" aria-label="Remove dependency {{ $dependency->title }}">×</button></form>@endcan</div>@empty<p class="text-sm text-slate-500">No prerequisites.</p>@endforelse</div></div>
                @if($task->dependents->isNotEmpty())<div class="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Blocking</p><div class="mt-2 flex flex-wrap gap-2">@foreach($task->dependents as $dependent)<a href="{{ route('app.tasks.show', $dependent) }}" class="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold hover:border-orbit-300 hover:text-orbit-700 dark:border-slate-700">{{ $dependent->title }}</a>@endforeach</div></div>@endif
                @can('update',$task) @if($dependencyCandidates->isNotEmpty())<form method="POST" action="{{ route('internal.task-dependencies.store',$task) }}" class="mt-4 space-y-2 border-t border-slate-100 pt-4 dark:border-slate-800">@csrf<x-label for="dependency_public_id">Add prerequisite</x-label><x-select id="dependency_public_id" name="dependency_public_id" required><option value="">Choose task…</option>@foreach($dependencyCandidates as $candidate)<option value="{{ $candidate->public_id }}">{{ $candidate->title }}@if($candidate->project_id !== $task->project_id) ({{ $candidate->project?->name }})@endif</option>@endforeach</x-select><div class="grid grid-cols-2 gap-2"><div><x-label for="dependency_type">Type</x-label><x-select id="dependency_type" name="type">@foreach($dependencyTypes as $type)<option value="{{ $type->value }}" @selected($type->value === 'fs')">{{ $type->label() }}</option>@endforeach</x-select></div><div><x-label for="lag_minutes">Lag (min)</x-label><x-input id="lag_minutes" type="number" name="lag_minutes" min="0" value="0" /></div></div><x-button class="w-full" aria-label="Add dependency">Add dependency</x-button><x-field-error name="dependency_public_id" /></form>@endif @endcan
            </section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" aria-labelledby="time-title">
                <div class="flex items-center justify-between gap-3"><h3 id="time-title" class="font-bold">Time tracking</h3><span class="text-xs font-bold tabular-nums text-slate-500">{{ $loggedMinutes }} min logged</span></div>
                <div class="mt-4 space-y-2">@forelse($task->timeEntries as $entry)<div class="flex items-start justify-between gap-3 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div class="min-w-0"><p class="font-semibold">{{ $entry->minutes }} min · {{ $entry->user->name }}</p><p class="text-xs text-slate-400">{{ $entry->worked_on->format('M j, Y') }}@if($entry->note) · {{ $entry->note }}@endif</p></div>@can('update',$task)<form method="POST" action="{{ route('internal.task-time-entries.destroy', $entry) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600">×</button></form>@endcan</div>@empty<p class="text-sm text-slate-500">No time logged yet.</p>@endforelse</div>
                @can('update',$task)<form method="POST" action="{{ route('internal.task-time-entries.store', $task) }}" class="mt-4 space-y-2 border-t border-slate-100 pt-4 dark:border-slate-800">@csrf<div class="grid grid-cols-2 gap-2"><div><x-label for="time-minutes">Minutes</x-label><x-input id="time-minutes" type="number" name="minutes" min="1" max="1440" required /></div><div><x-label for="worked_on">Worked on</x-label><x-input id="worked_on" type="date" name="worked_on" value="{{ now()->toDateString() }}" required /></div></div><x-input name="note" placeholder="Optional note" maxlength="500" /><x-button class="w-full" variant="secondary">Log time</x-button></form>@endcan
            </section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">Checklist</h3><div class="mt-4 space-y-2">@forelse($task->checklistItems as $item)<div class="rounded-xl border border-slate-100 p-3 dark:border-slate-800">@can('update',$task)<form method="POST" action="{{ route('internal.task-checklist.update',$item) }}" class="flex items-center gap-2">@csrf @method('PATCH')<input type="hidden" name="is_completed" value="0"><input type="checkbox" name="is_completed" value="1" class="rounded text-orbit-600" @checked($item->is_completed) onchange="this.form.submit()"><input name="title" value="{{ $item->title }}" class="min-w-0 flex-1 border-0 bg-transparent p-0 text-sm focus:ring-0 {{ $item->is_completed ? 'line-through text-slate-400' : '' }}"><button class="text-xs font-semibold text-orbit-700">Save</button></form><form method="POST" action="{{ route('internal.task-checklist.destroy',$item) }}" class="mt-1 text-right">@csrf @method('DELETE')<button class="text-xs text-rose-600">Remove</button></form>@else<p class="text-sm {{ $item->is_completed ? 'line-through text-slate-400' : '' }}">{{ $item->title }}</p>@endcan</div>@empty<p class="text-sm text-slate-500">No checklist items.</p>@endforelse</div>@can('update',$task)<form method="POST" action="{{ route('internal.task-checklist.store',$task) }}" class="mt-4 flex gap-2">@csrf<x-input name="title" placeholder="Add checklist item" required/><x-button aria-label="Add checklist item"><x-icon name="plus"/></x-button></form>@endcan</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">Attachments</h3><div class="mt-4 space-y-2">@forelse($task->files as $file)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3 text-sm dark:border-slate-800"><div class="min-w-0"><a href="{{ route('internal.files.download',$file) }}" class="block truncate font-semibold hover:text-orbit-700">{{ $file->original_name }}</a><p class="text-xs text-slate-400">{{ number_format($file->size / 1024, 1) }} KB · {{ $file->uploader->name }}</p></div>@can('delete',$file)<form method="POST" action="{{ route('internal.files.destroy',$file) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Delete</button></form>@endcan</div>@empty<p class="text-sm text-slate-500">No attachments.</p>@endforelse</div>@can('update',$task)<form method="POST" action="{{ route('internal.task-attachments.store',$task) }}" enctype="multipart/form-data" class="mt-4 space-y-2">@csrf<input type="file" name="attachment" required class="block w-full text-xs"><x-button variant="secondary" class="w-full">Upload attachment</x-button></form>@endcan</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 text-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">At a glance</h3><dl class="mt-4 space-y-3"><div class="flex justify-between gap-3"><dt class="text-slate-500">Status</dt><dd class="font-semibold">{{ $task->status->name }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Milestone</dt><dd class="text-right font-semibold">{{ $task->milestone?->name ?? 'None' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Due</dt><dd class="font-semibold">{{ $task->due_at?->format('M j, Y H:i') ?? 'Not set' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Baseline</dt><dd class="text-right font-semibold">{{ $task->baseline_due_at?->format('M j, Y') ?? 'None' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Estimate</dt><dd class="font-semibold">{{ $task->estimate_minutes ? $task->estimate_minutes.' min' : 'Not set' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Logged</dt><dd class="font-semibold">{{ $loggedMinutes }} min</dd></div><div><dt class="text-slate-500">Assignees</dt><dd class="mt-1 font-semibold">{{ $task->assignees->pluck('name')->join(', ') ?: 'Unassigned' }}</dd></div></dl></section>
        </aside>
    </div>
@endsection
