@extends('layouts.app')

@section('title', $task->title)
@section('page-title', 'Task detail')

@section('content')
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ $task->project->taskListUrl() }}" class="text-sm font-semibold text-slate-500 hover:text-orbit-700">← {{ $task->project->isPersonal() ? 'My tasks' : $task->project->name }}</a><div class="mt-3 flex flex-wrap items-center gap-3"><span class="size-2.5 rounded-full" style="background:{{ $task->status->color }}"></span><h2 class="text-2xl font-bold tracking-tight">{{ $task->title }}</h2><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-800">{{ $task->priority->label() }}</span></div></div><div class="flex gap-2">@can('update',$task)<form method="POST" action="{{ route('internal.tasks.duplicate',$task) }}">@csrf<x-button variant="secondary">Duplicate</x-button></form>@endcan @can('delete',$task)<form method="POST" action="{{ route('internal.tasks.destroy',$task) }}" onsubmit="return confirm('Archive this task?')">@csrf @method('DELETE')<input type="hidden" name="return_to" value="{{ $task->project->taskListUrl() }}"><x-button variant="danger">Archive</x-button></form>@endcan</div></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
        <div class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 dark:border-slate-800 dark:bg-slate-900">
                <div class="flex items-center justify-between"><h3 class="text-lg font-bold">Task details</h3><span class="text-xs text-slate-400">Version {{ $task->version }}</span></div>
                @can('update',$task)<div class="mt-6">@include('app.tasks._form', ['formPrefix' => 'edit-task', 'project' => $task->project, 'statuses' => $task->project->taskStatuses, 'defaultStatus' => $task->status])</div>@else<div class="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600">{{ $task->description ?: 'No description.' }}</div>@endcan
            </section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 dark:border-slate-800 dark:bg-slate-900" aria-labelledby="comments-title">
                <h3 id="comments-title" class="text-lg font-bold">Comments</h3>
                @can('update',$task)<form method="POST" action="{{ route('internal.task-comments.store',$task) }}" class="mt-4">@csrf<x-textarea name="body" rows="3" placeholder="Write a comment…" required></x-textarea><div class="mt-2 text-right"><x-button>Add comment</x-button></div></form>@endcan
                <div class="mt-6 space-y-4">@forelse($task->comments as $comment)<article class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold">{{ $comment->author->name }}</p><time class="text-xs text-slate-400">{{ $comment->created_at->diffForHumans() }} @if($comment->edited_at)· edited @endif</time></div>@can('delete',$comment)<form method="POST" action="{{ route('internal.task-comments.destroy',$comment) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Delete</button></form>@endcan</div><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $comment->body }}</p>@can('update',$comment)<details class="mt-3"><summary class="cursor-pointer text-xs font-semibold text-orbit-700">Edit</summary><form method="POST" action="{{ route('internal.task-comments.update',$comment) }}" class="mt-2">@csrf @method('PATCH')<x-textarea name="body" rows="2">{{ $comment->body }}</x-textarea><x-button class="mt-2" variant="secondary">Save comment</x-button></form></details>@endcan</article>@empty<p class="text-sm text-slate-500">No comments yet.</p>@endforelse</div>
            </section>
        </div>
        <aside class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">Checklist</h3><div class="mt-4 space-y-2">@forelse($task->checklistItems as $item)<div class="rounded-xl border border-slate-100 p-3 dark:border-slate-800">@can('update',$task)<form method="POST" action="{{ route('internal.task-checklist.update',$item) }}" class="flex items-center gap-2">@csrf @method('PATCH')<input type="hidden" name="is_completed" value="0"><input type="checkbox" name="is_completed" value="1" class="rounded text-orbit-600" @checked($item->is_completed) onchange="this.form.submit()"><input name="title" value="{{ $item->title }}" class="min-w-0 flex-1 border-0 bg-transparent p-0 text-sm focus:ring-0 {{ $item->is_completed ? 'line-through text-slate-400' : '' }}"><button class="text-xs font-semibold text-orbit-700">Save</button></form><form method="POST" action="{{ route('internal.task-checklist.destroy',$item) }}" class="mt-1 text-right">@csrf @method('DELETE')<button class="text-xs text-rose-600">Remove</button></form>@else<p class="text-sm {{ $item->is_completed ? 'line-through text-slate-400' : '' }}">{{ $item->title }}</p>@endcan</div>@empty<p class="text-sm text-slate-500">No checklist items.</p>@endforelse</div>@can('update',$task)<form method="POST" action="{{ route('internal.task-checklist.store',$task) }}" class="mt-4 flex gap-2">@csrf<x-input name="title" placeholder="Add checklist item" required/><x-button aria-label="Add checklist item"><x-icon name="plus"/></x-button></form>@endcan</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">Attachments</h3><div class="mt-4 space-y-2">@forelse($task->files as $file)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3 text-sm dark:border-slate-800"><div class="min-w-0"><a href="{{ route('internal.files.download',$file) }}" class="block truncate font-semibold hover:text-orbit-700">{{ $file->original_name }}</a><p class="text-xs text-slate-400">{{ number_format($file->size / 1024, 1) }} KB · {{ $file->uploader->name }}</p></div>@can('delete',$file)<form method="POST" action="{{ route('internal.files.destroy',$file) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Delete</button></form>@endcan</div>@empty<p class="text-sm text-slate-500">No attachments.</p>@endforelse</div>@can('update',$task)<form method="POST" action="{{ route('internal.task-attachments.store',$task) }}" enctype="multipart/form-data" class="mt-4 space-y-2">@csrf<input type="file" name="attachment" required class="block w-full text-xs"><x-button variant="secondary" class="w-full">Upload attachment</x-button></form>@endcan</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 text-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">At a glance</h3><dl class="mt-4 space-y-3"><div class="flex justify-between gap-3"><dt class="text-slate-500">Status</dt><dd class="font-semibold">{{ $task->status->name }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Milestone</dt><dd class="text-right font-semibold">{{ $task->milestone?->name ?? 'None' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Due</dt><dd class="font-semibold">{{ $task->due_at?->format('M j, Y H:i') ?? 'Not set' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Baseline</dt><dd class="text-right font-semibold">{{ $task->baseline_due_at?->format('M j, Y') ?? 'None' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Estimate</dt><dd class="font-semibold">{{ $task->estimate_minutes ? $task->estimate_minutes.' min' : 'Not set' }}</dd></div><div><dt class="text-slate-500">Assignees</dt><dd class="mt-1 font-semibold">{{ $task->assignees->pluck('name')->join(', ') ?: 'Unassigned' }}</dd></div></dl></section>
        </aside>
    </div>
@endsection
