<?php

use App\Http\Controllers\InternalApi\AiDescriptionController;
use App\Http\Controllers\InternalApi\AiMessageController;
use App\Http\Controllers\InternalApi\ApprovalDelegationController;
use App\Http\Controllers\InternalApi\AvatarController;
use App\Http\Controllers\InternalApi\BulkTaskController;
use App\Http\Controllers\InternalApi\CalendarController;
use App\Http\Controllers\InternalApi\ConversationController;
use App\Http\Controllers\InternalApi\ConversationMessageController;
use App\Http\Controllers\InternalApi\ConversationReadController;
use App\Http\Controllers\InternalApi\DashboardController;
use App\Http\Controllers\InternalApi\DashboardWidgetController;
use App\Http\Controllers\InternalApi\FeatureController;
use App\Http\Controllers\InternalApi\FileController;
use App\Http\Controllers\InternalApi\IntegrationController;
use App\Http\Controllers\InternalApi\MasterDataController;
use App\Http\Controllers\InternalApi\MessageController;
use App\Http\Controllers\InternalApi\MessageReactionController;
use App\Http\Controllers\InternalApi\NotificationController;
use App\Http\Controllers\InternalApi\NotificationPreferenceController;
use App\Http\Controllers\InternalApi\PasswordController;
use App\Http\Controllers\InternalApi\PerformanceController;
use App\Http\Controllers\InternalApi\ProfileController;
use App\Http\Controllers\InternalApi\ProjectController;
use App\Http\Controllers\InternalApi\ProjectMemberController;
use App\Http\Controllers\InternalApi\ProjectMilestoneController;
use App\Http\Controllers\InternalApi\ProjectPlanningController;
use App\Http\Controllers\InternalApi\ProjectTemplateController;
use App\Http\Controllers\InternalApi\PushSubscriptionController;
use App\Http\Controllers\InternalApi\ReportController;
use App\Http\Controllers\InternalApi\RequestAttachmentController;
use App\Http\Controllers\InternalApi\RequestMonitoringController;
use App\Http\Controllers\InternalApi\ScheduleEventController;
use App\Http\Controllers\InternalApi\SessionController;
use App\Http\Controllers\InternalApi\SupportingTaskController;
use App\Http\Controllers\InternalApi\SupportTicketController;
use App\Http\Controllers\InternalApi\TaskAttachmentController;
use App\Http\Controllers\InternalApi\TaskBreakdownController;
use App\Http\Controllers\InternalApi\TaskCategoryController;
use App\Http\Controllers\InternalApi\TaskChecklistController;
use App\Http\Controllers\InternalApi\TaskCommentController;
use App\Http\Controllers\InternalApi\TaskController;
use App\Http\Controllers\InternalApi\TaskDependencyController;
use App\Http\Controllers\InternalApi\TaskFieldController;
use App\Http\Controllers\InternalApi\TaskMoveController;
use App\Http\Controllers\InternalApi\TaskPropertyController;
use App\Http\Controllers\InternalApi\TaskStatusController;
use App\Http\Controllers\InternalApi\TaskTimeEntryController;
use App\Http\Controllers\InternalApi\TaskViewController;
use App\Http\Controllers\InternalApi\TwoFactorController;
use App\Http\Controllers\InternalApi\UserAccountController;
use App\Http\Controllers\InternalApi\WorkspaceController;
use App\Http\Controllers\InternalApi\WorkspaceInvitationController;
use App\Http\Controllers\InternalApi\WorkspaceMemberController;
use App\Http\Controllers\InternalApi\WorkspaceOwnershipController;
use Illuminate\Support\Facades\Route;

Route::post('/workspaces', [WorkspaceController::class, 'store'])->name('internal.workspaces.store');
Route::patch('/workspaces/{workspace}', [WorkspaceController::class, 'update'])->name('internal.workspaces.update');
Route::post('/workspaces/{workspace}/invitations', [WorkspaceInvitationController::class, 'store'])->middleware('throttle:10,1')->name('internal.invitations.store');
Route::post('/invitations/{token}/accept', [WorkspaceInvitationController::class, 'accept'])->name('internal.invitations.accept');
Route::post('/invitations/{token}/reject', [WorkspaceInvitationController::class, 'reject'])->name('internal.invitations.reject');
Route::patch('/workspace-members/{member}', [WorkspaceMemberController::class, 'update'])->name('internal.workspace-members.update');
Route::delete('/workspace-members/{member}', [WorkspaceMemberController::class, 'destroy'])->name('internal.workspace-members.destroy');
Route::delete('/workspace-members/{member}/account', [UserAccountController::class, 'destroy'])->name('internal.user-accounts.destroy');
Route::post('/workspaces/{workspace}/approval-delegations', [ApprovalDelegationController::class, 'store'])->name('internal.approval-delegations.store');
Route::delete('/approval-delegations/{approvalDelegation}', [ApprovalDelegationController::class, 'destroy'])->name('internal.approval-delegations.destroy');
Route::post('/projects/{project}/task-views', [TaskViewController::class, 'store'])->name('internal.task-views.store');
Route::delete('/task-views/{taskView}', [TaskViewController::class, 'destroy'])->name('internal.task-views.destroy');
Route::post('/projects/{project}/templates', [ProjectTemplateController::class, 'store'])->name('internal.project-templates.store');
Route::delete('/project-templates/{projectTemplate}', [ProjectTemplateController::class, 'destroy'])->name('internal.project-templates.destroy');
Route::post('/workspaces/{workspace}/transfer-ownership', [WorkspaceOwnershipController::class, 'store'])->name('internal.workspaces.transfer');
Route::get('/workspaces/{workspace}/dashboard', [DashboardController::class, 'index'])->name('internal.dashboard.index');
Route::get('/workspaces/{workspace}/dashboard/widgets/insights', [DashboardWidgetController::class, 'insights'])->name('internal.dashboard.widgets.insights');
Route::get('/workspaces/{workspace}/performance', [PerformanceController::class, 'index'])->name('internal.performance.index');
Route::post('/workspaces/{workspace}/ai/descriptions', [AiDescriptionController::class, 'store'])->middleware('throttle:10,1')->name('internal.ai.descriptions.store');
Route::post('/workspaces/{workspace}/ask-ai/messages', [AiMessageController::class, 'store'])->middleware('throttle:12,1')->name('internal.ai.messages.store');
Route::get('/workspaces/{workspace}/reports.csv', [ReportController::class, 'csv'])->name('internal.reports.csv');
Route::get('/workspaces/{workspace}/reports.pdf', [ReportController::class, 'pdf'])->name('internal.reports.pdf');

Route::get('/workspaces/{workspace}/conversations', [ConversationController::class, 'index'])->name('internal.conversations.index');
Route::post('/workspaces/{workspace}/conversations', [ConversationController::class, 'store'])->name('internal.conversations.store');
Route::get('/conversations/{conversation}/messages', [ConversationMessageController::class, 'index'])->name('internal.messages.index');
Route::post('/conversations/{conversation}/messages', [ConversationMessageController::class, 'store'])->middleware('throttle:60,1')->name('internal.messages.store');
Route::patch('/messages/{message}', [MessageController::class, 'update'])->name('internal.messages.update');
Route::delete('/messages/{message}', [MessageController::class, 'destroy'])->name('internal.messages.destroy');
Route::post('/messages/{message}/reactions', [MessageReactionController::class, 'store'])->name('internal.message-reactions.store');
Route::post('/conversations/{conversation}/read', [ConversationReadController::class, 'store'])->name('internal.conversations.read');
Route::get('/notifications', [NotificationController::class, 'index'])->name('internal.notifications.index');
Route::get('/requests/{featureRequest}/monitoring', [RequestMonitoringController::class, 'feature'])->name('internal.requests.monitoring');
Route::get('/project-requests/{projectRequest}/monitoring', [RequestMonitoringController::class, 'project'])->name('internal.project-requests.monitoring');
Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('internal.notifications.read-all');
Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('internal.notifications.read');
Route::patch('/notification-preferences', [NotificationPreferenceController::class, 'update'])->name('internal.notification-preferences.update');
Route::post('/push-subscriptions', [PushSubscriptionController::class, 'store'])->name('internal.push-subscriptions.store');
Route::delete('/push-subscriptions', [PushSubscriptionController::class, 'destroy'])->name('internal.push-subscriptions.destroy');

Route::patch('/settings/profile', [ProfileController::class, 'update'])->name('internal.settings.profile.update');
Route::patch('/settings/theme', [ProfileController::class, 'theme'])->name('internal.settings.theme.update');
Route::put('/settings/password', [PasswordController::class, 'update'])->middleware('throttle:6,1')->name('internal.settings.password.update');
Route::get('/users/{user}/avatar', [AvatarController::class, 'show'])->name('internal.users.avatar');
Route::post('/security/two-factor/enable', [TwoFactorController::class, 'enable'])->middleware('throttle:6,1')->name('internal.security.two-factor.enable');
Route::post('/security/two-factor/confirm', [TwoFactorController::class, 'confirm'])->middleware('throttle:10,1')->name('internal.security.two-factor.confirm');
Route::delete('/security/two-factor', [TwoFactorController::class, 'disable'])->name('internal.security.two-factor.disable');
Route::post('/security/recovery-codes', [TwoFactorController::class, 'recoveryCodes'])->name('internal.security.recovery-codes');
Route::delete('/security/sessions/others', [SessionController::class, 'destroyOthers'])->name('internal.security.sessions.others');
Route::delete('/security/sessions/{session}', [SessionController::class, 'destroy'])->name('internal.security.sessions.destroy');
Route::get('/integrations/{provider}/redirect', [IntegrationController::class, 'redirect'])->middleware('throttle:10,1')->name('internal.integrations.redirect');
Route::get('/integrations/{provider}/callback', [IntegrationController::class, 'callback'])->middleware('throttle:10,1')->name('internal.integrations.callback');
Route::post('/integrations/{connection}/action', [IntegrationController::class, 'action'])->name('internal.integrations.action');
Route::delete('/integrations/{connection}', [IntegrationController::class, 'destroy'])->name('internal.integrations.destroy');
Route::post('/workspaces/{workspace}/support-tickets', [SupportTicketController::class, 'store'])->middleware('throttle:6,1')->name('internal.support-tickets.store');
Route::post('/workspaces/{workspace}/supporting-tasks', [SupportingTaskController::class, 'store'])->name('internal.supporting-tasks.store');
Route::patch('/supporting-tasks/{supportingTask}', [SupportingTaskController::class, 'update'])->name('internal.supporting-tasks.update');
Route::delete('/supporting-tasks/{supportingTask}', [SupportingTaskController::class, 'destroy'])->name('internal.supporting-tasks.destroy');

Route::post('/workspaces/{workspace}/projects', [ProjectController::class, 'store'])->name('internal.projects.store');
Route::post('/workspaces/{workspace}/features', [FeatureController::class, 'store'])->name('internal.features.store');
Route::patch('/projects/{project}', [ProjectController::class, 'update'])->name('internal.projects.update');
Route::delete('/projects/{project}', [ProjectController::class, 'destroy'])->name('internal.projects.destroy');
Route::post('/projects/{project}/restore', [ProjectController::class, 'restore'])->withTrashed()->name('internal.projects.restore');
Route::post('/projects/{project}/members', [ProjectMemberController::class, 'store'])->name('internal.project-members.store');
Route::patch('/projects/{project}/members/{member}', [ProjectMemberController::class, 'update'])->name('internal.project-members.update');
Route::delete('/projects/{project}/members/{member}', [ProjectMemberController::class, 'destroy'])->name('internal.project-members.destroy');

Route::get('/projects/{project}/tasks', [TaskController::class, 'index'])->name('internal.tasks.index');
Route::post('/projects/{project}/tasks', [TaskController::class, 'store'])->name('internal.tasks.store');
Route::post('/projects/{project}/tasks/bulk', [BulkTaskController::class, 'store'])->name('internal.tasks.bulk');
Route::get('/tasks/{task}', [TaskController::class, 'show'])->name('internal.tasks.show');
Route::patch('/tasks/{task}', [TaskController::class, 'update'])->name('internal.tasks.update');
Route::patch('/tasks/{task}/field', [TaskController::class, 'updateField'])->name('internal.tasks.fields.update');
Route::delete('/tasks/{task}', [TaskController::class, 'destroy'])->name('internal.tasks.destroy');
Route::post('/tasks/{task}/restore', [TaskController::class, 'restore'])->withTrashed()->name('internal.tasks.restore');
Route::post('/tasks/{task}/duplicate', [TaskController::class, 'duplicate'])->name('internal.tasks.duplicate');
Route::post('/tasks/{task}/move', [TaskMoveController::class, 'store'])->name('internal.tasks.move');
Route::post('/tasks/{task}/dependencies', [TaskDependencyController::class, 'store'])->name('internal.task-dependencies.store');
Route::delete('/tasks/{task}/dependencies/{dependency}', [TaskDependencyController::class, 'destroy'])->name('internal.task-dependencies.destroy');
Route::post('/tasks/{task}/time-entries', [TaskTimeEntryController::class, 'store'])->name('internal.task-time-entries.store');
Route::delete('/time-entries/{entry}', [TaskTimeEntryController::class, 'destroy'])->name('internal.task-time-entries.destroy');

Route::post('/projects/{project}/milestones', [ProjectMilestoneController::class, 'store'])->name('internal.project-milestones.store');
Route::patch('/milestones/{milestone}', [ProjectMilestoneController::class, 'update'])->name('internal.project-milestones.update');
Route::delete('/milestones/{milestone}', [ProjectMilestoneController::class, 'destroy'])->name('internal.project-milestones.destroy');
Route::post('/projects/{project}/baseline', [ProjectPlanningController::class, 'baseline'])->name('internal.projects.baseline');
Route::post('/projects/{project}/reschedule', [ProjectPlanningController::class, 'reschedule'])->name('internal.projects.reschedule');

Route::post('/projects/{project}/statuses', [TaskStatusController::class, 'store'])->name('internal.task-statuses.store');
Route::patch('/task-statuses/{status}', [TaskStatusController::class, 'update'])->name('internal.task-statuses.update');
Route::delete('/task-statuses/{status}', [TaskStatusController::class, 'destroy'])->name('internal.task-statuses.destroy');
Route::post('/projects/{project}/statuses/reorder', [TaskStatusController::class, 'reorder'])->name('internal.task-statuses.reorder');
Route::post('/projects/{project}/task-properties', [TaskPropertyController::class, 'store'])->name('internal.task-properties.store');
Route::patch('/projects/{project}/task-fields/{field}', [TaskFieldController::class, 'update'])->name('internal.task-fields.update');
Route::patch('/task-properties/{property}', [TaskPropertyController::class, 'update'])->name('internal.task-properties.update');
Route::delete('/task-properties/{property}', [TaskPropertyController::class, 'destroy'])->name('internal.task-properties.destroy');
Route::put('/tasks/{task}/task-properties/{property}', [TaskPropertyController::class, 'updateValue'])->name('internal.task-properties.values.update');
Route::post('/workspaces/{workspace}/task-categories', [TaskCategoryController::class, 'store'])->name('internal.task-categories.store');

// Master data (PRD-08). Reference rows archive, never delete.
Route::patch('/task-categories/{category}', [MasterDataController::class, 'updateCategory'])->name('internal.master.categories.update');
Route::post('/task-categories/{category}/archive', [MasterDataController::class, 'archiveCategory'])->name('internal.master.categories.archive');
Route::post('/task-categories/{category}/restore', [MasterDataController::class, 'restoreCategory'])->name('internal.master.categories.restore');
Route::post('/workspaces/{workspace}/status-templates', [MasterDataController::class, 'storeStatusTemplate'])->name('internal.master.status-templates.store');
Route::patch('/status-templates/{template}', [MasterDataController::class, 'updateStatusTemplate'])->name('internal.master.status-templates.update');
Route::post('/status-templates/{template}/archive', [MasterDataController::class, 'archiveStatusTemplate'])->name('internal.master.status-templates.archive');
Route::post('/workspaces/{workspace}/capacity', [MasterDataController::class, 'saveCapacity'])->name('internal.master.capacity.save');
Route::post('/workspaces/{workspace}/capacity-exceptions', [MasterDataController::class, 'storeException'])->name('internal.master.exceptions.store');
Route::delete('/capacity-exceptions/{exception}', [MasterDataController::class, 'destroyException'])->name('internal.master.exceptions.destroy');
Route::post('/workspaces/{workspace}/holidays', [MasterDataController::class, 'storeHoliday'])->name('internal.master.holidays.store');
Route::delete('/holidays/{holiday}', [MasterDataController::class, 'destroyHoliday'])->name('internal.master.holidays.destroy');
Route::post('/workspaces/{workspace}/request-rules', [MasterDataController::class, 'saveRules'])->name('internal.master.rules.save');
Route::post('/workspaces/{workspace}/systems', [MasterDataController::class, 'storeSystem'])->name('internal.master.systems.store');
Route::patch('/systems/{system}', [MasterDataController::class, 'updateSystem'])->name('internal.master.systems.update');
Route::post('/systems/{system}/archive', [MasterDataController::class, 'archiveSystem'])->name('internal.master.systems.archive');
// One PIC per department, keyed by the department: a system serves several, each with its own.
Route::post('/systems/{system}/pics', [MasterDataController::class, 'assignSystemPic'])->name('internal.master.systems.pics.assign');
Route::delete('/systems/{system}/pics', [MasterDataController::class, 'removeSystemPic'])->name('internal.master.systems.pics.remove');
Route::post('/support-articles', [MasterDataController::class, 'storeArticle'])->name('internal.master.articles.store');
Route::patch('/support-articles/{article}', [MasterDataController::class, 'updateArticle'])->name('internal.master.articles.update');
Route::post('/support-articles/{article}/archive', [MasterDataController::class, 'archiveArticle'])->name('internal.master.articles.archive');

Route::post('/tasks/{task}/checklist', [TaskChecklistController::class, 'store'])->name('internal.task-checklist.store');
Route::patch('/task-checklist-items/{item}', [TaskChecklistController::class, 'update'])->name('internal.task-checklist.update');
Route::delete('/task-checklist-items/{item}', [TaskChecklistController::class, 'destroy'])->name('internal.task-checklist.destroy');
Route::post('/tasks/{task}/comments', [TaskCommentController::class, 'store'])->name('internal.task-comments.store');
Route::patch('/task-comments/{comment}', [TaskCommentController::class, 'update'])->name('internal.task-comments.update');
Route::delete('/task-comments/{comment}', [TaskCommentController::class, 'destroy'])->name('internal.task-comments.destroy');
Route::post('/tasks/{task}/attachments', [TaskAttachmentController::class, 'store'])->middleware('throttle:20,1')->name('internal.task-attachments.store');
Route::post('/workspaces/{workspace}/files', [FileController::class, 'store'])->middleware('throttle:20,1')->name('internal.files.store');
Route::get('/files/{file}/download', [FileController::class, 'download'])->name('internal.files.download');
Route::get('/files/{file}/preview', [FileController::class, 'preview'])->name('internal.files.preview');
Route::patch('/files/{file}', [FileController::class, 'update'])->name('internal.files.update');
Route::delete('/files/{file}', [FileController::class, 'destroy'])->name('internal.files.destroy');

Route::post('/requests/{featureRequest}/attachments', [RequestAttachmentController::class, 'storeForFeature'])->name('internal.requests.attachments.store');
Route::post('/project-requests/{projectRequest}/attachments', [RequestAttachmentController::class, 'storeForProject'])->name('internal.project-requests.attachments.store');
Route::delete('/request-attachments/{file}', [RequestAttachmentController::class, 'destroy'])->name('internal.request-attachments.destroy');

Route::post('/task-breakdowns/{breakdown}/accept', [TaskBreakdownController::class, 'accept'])->name('internal.breakdowns.accept');
Route::post('/task-breakdowns/{breakdown}/regenerate', [TaskBreakdownController::class, 'regenerate'])->name('internal.breakdowns.regenerate');
Route::post('/task-breakdowns/{breakdown}/discard', [TaskBreakdownController::class, 'discard'])->name('internal.breakdowns.discard');
Route::post('/task-breakdowns/{breakdown}/preview', [TaskBreakdownController::class, 'preview'])->name('internal.breakdowns.preview');

Route::get('/workspaces/{workspace}/calendar', [CalendarController::class, 'index'])->name('internal.calendar.index');
Route::post('/workspaces/{workspace}/schedule-events', [ScheduleEventController::class, 'store'])->name('internal.schedule-events.store');
Route::patch('/schedule-events/{event}', [ScheduleEventController::class, 'update'])->name('internal.schedule-events.update');
Route::delete('/schedule-events/{event}', [ScheduleEventController::class, 'destroy'])->name('internal.schedule-events.destroy');
