@extends('layouts.app')

@section('title', $membership->user->name)
@section('page-title', 'Member details')

@section('content')
    <div>
        <a href="{{ route('app.workspaces.team', $workspace) }}" class="text-sm font-semibold text-orbit-700 dark:text-orbit-300">← Back to team</a>
        <section class="mt-5 flex flex-col gap-5 rounded-3xl border border-slate-200 bg-white p-6 sm:flex-row sm:items-center dark:border-slate-800 dark:bg-slate-900"><x-avatar :src="$membership->user->avatar_path ? route('internal.users.avatar', $membership->user) : null" :name="$membership->user->name" size="size-20" /><div class="min-w-0 flex-1"><h2 class="text-3xl font-bold tracking-tight">{{ $membership->user->name }}</h2><p class="mt-1 text-slate-500">{{ $membership->user->job_title ?: 'Team member' }} · {{ $membership->user->email }}</p><div class="mt-4 flex flex-wrap gap-2"><x-badge>{{ $membership->role->label() }}</x-badge><x-badge :tone="$membership->user->last_seen_at?->gte(now()->subMinutes(5)) ? 'success' : 'slate'">{{ $membership->user->last_seen_at?->gte(now()->subMinutes(5)) ? 'Online' : 'Offline' }}</x-badge></div></div></section>

        <div class="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">@foreach([['Assigned tasks',$stats['assigned']],['Active tasks',$stats['active']],['Completed',$stats['completed']],['Overdue',$stats['overdue']]] as [$label,$value])<section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold">{{ $value }}</p></section>@endforeach</div>

        <div class="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]">
            <section class="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-xl font-bold">Recent assigned work</h2><div class="mt-5 space-y-3">@forelse($tasks as $task)<a href="{{ route('app.tasks.show', $task) }}" class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-4 hover:border-orbit-300 dark:border-slate-800"><span class="min-w-0"><strong class="block truncate text-sm">{{ $task->title }}</strong><span class="mt-1 block truncate text-xs text-slate-500">{{ $task->project->name }} · {{ $task->status->name }}</span></span><x-badge :tone="$task->completed_at ? 'success' : ($task->due_at?->isPast() ? 'danger' : 'slate')">{{ $task->completed_at ? 'Done' : ($task->due_at?->isPast() ? 'Overdue' : $task->priority->label()) }}</x-badge></a>@empty<p class="text-sm text-slate-500">No accessible tasks are assigned to this member.</p>@endforelse</div><x-pagination :paginator="$tasks" class="mt-5" /></section>
            <div class="space-y-6"><section class="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-lg font-bold">Visible projects</h2><div class="mt-4 space-y-3">@forelse($projects as $project)<a href="{{ route('app.projects.show', $project) }}" class="block rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><span class="font-semibold">{{ $project->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $project->assigned_tasks_count }} assigned tasks</span></a>@empty<p class="text-sm text-slate-500">No visible project membership.</p>@endforelse</div></section><section class="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-lg font-bold">Recent activity</h2><div class="mt-4 space-y-4">@forelse($activity as $entry)<div class="border-l-2 border-orbit-300 pl-3"><p class="text-sm font-semibold">{{ str($entry->action)->replace('.', ' ')->headline() }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-slate-500">No recent activity recorded.</p>@endforelse</div></section></div>
        </div>
    </div>
@endsection
